"""Curated technical skill catalog and role signatures."""

SKILL_ALIASES = {
    "Python": ["python"],
    "NLP": ["nlp", "natural language processing"],
    "Machine Learning": ["machine learning", "ml"],
    "Deep Learning": ["deep learning"],
    "Generative AI": ["generative ai", "gen ai"],
    "LLMs": ["llms", "large language models", "llm"],
    "LangChain": ["langchain"],
    "OpenAI API": ["openai api", "openai"],
    "FastAPI": ["fastapi"],
    "Flask": ["flask"],
    "Django": ["django"],
    "REST API": ["rest api", "restful api", "api development", "backend api", "backend apis"],
    "Microservices": ["microservices", "microservice architecture"],
    "Pandas": ["pandas"],
    "NumPy": ["numpy"],
    "Scikit-learn": ["scikit-learn", "sklearn"],
    "spaCy": ["spacy"],
    "NLTK": ["nltk"],
    "TensorFlow": ["tensorflow"],
    "PyTorch": ["pytorch"],
    "TF-IDF": ["tf-idf", "tfidf"],
    "Cosine Similarity": ["cosine similarity"],
    "Regex": ["regex", "regular expressions"],
    "Resume Parsing": ["resume parsing", "resume parser"],
    "Candidate Screening": ["candidate screening", "resume screening"],
    "OCR": ["ocr", "optical character recognition"],
    "Data Analysis": ["data analysis", "data analytics"],
    "Data Visualization": ["data visualization", "matplotlib", "seaborn", "plotly"],
    "Power BI": ["power bi"],
    "Tableau": ["tableau"],
    "SQL": ["sql"],
    "MySQL": ["mysql"],
    "PostgreSQL": ["postgresql", "postgres", "psql"],
    "MongoDB": ["mongodb", "mongo db", "mongo"],
    "SQLite": ["sqlite"],
    "Redis": ["redis"],
    "Kafka": ["kafka", "apache kafka"],
    "Spark": ["spark", "apache spark"],
    "Airflow": ["airflow", "apache airflow"],
    "ETL": ["etl", "data pipeline", "data pipelines"],
    "AWS": ["aws", "amazon web services"],
    "Azure": ["azure", "microsoft azure"],
    "GCP": ["gcp", "google cloud"],
    "Docker": ["docker", "containerization"],
    "Kubernetes": ["kubernetes", "k8s"],
    "Git": ["git", "github", "gitlab", "version control"],
    "Linux": ["linux", "unix"],
    "CI/CD": ["ci/cd", "continuous integration", "continuous delivery", "jenkins", "github actions"],
    "Java": ["java"],
    "JavaScript": ["javascript", "js"],
    "TypeScript": ["typescript", "ts"],
    "C++": ["c++"],
    "C#": ["c#"],
    "HTML": ["html", "html5"],
    "CSS": ["css", "css3"],
    "React": ["react", "reactjs", "react.js"],
    "Node.js": ["node.js", "nodejs"],
    "Express.js": ["express", "express.js"],
    "Authentication": ["authentication", "authorization", "oauth", "jwt"],
    "Streamlit": ["streamlit"],
    "Selenium": ["selenium"],
    "Testing": ["testing", "unit testing", "integration testing", "pytest", "unittest"],
    "Problem Solving": ["problem solving"],
    "Communication": ["communication", "stakeholder communication"],
}

SKILL_CATEGORY_MAP = {
    "Python": "Programming",
    "Java": "Programming",
    "JavaScript": "Programming",
    "TypeScript": "Programming",
    "C++": "Programming",
    "C#": "Programming",
    "NLP": "AI & NLP",
    "Machine Learning": "AI & NLP",
    "Deep Learning": "AI & NLP",
    "Generative AI": "AI & NLP",
    "LLMs": "AI & NLP",
    "LangChain": "AI & NLP",
    "OpenAI API": "AI & NLP",
    "Scikit-learn": "AI & NLP",
    "spaCy": "AI & NLP",
    "NLTK": "AI & NLP",
    "TensorFlow": "AI & NLP",
    "PyTorch": "AI & NLP",
    "TF-IDF": "AI & NLP",
    "Cosine Similarity": "AI & NLP",
    "Regex": "AI & NLP",
    "Resume Parsing": "AI & NLP",
    "Candidate Screening": "AI & NLP",
    "OCR": "AI & NLP",
    "FastAPI": "Backend & APIs",
    "Flask": "Backend & APIs",
    "Django": "Backend & APIs",
    "REST API": "Backend & APIs",
    "Microservices": "Backend & APIs",
    "Node.js": "Backend & APIs",
    "Express.js": "Backend & APIs",
    "Authentication": "Backend & APIs",
    "Pandas": "Data & Analytics",
    "NumPy": "Data & Analytics",
    "Data Analysis": "Data & Analytics",
    "Data Visualization": "Data & Analytics",
    "Power BI": "Data & Analytics",
    "Tableau": "Data & Analytics",
    "Spark": "Data & Analytics",
    "Airflow": "Data & Analytics",
    "ETL": "Data & Analytics",
    "SQL": "Databases",
    "MySQL": "Databases",
    "PostgreSQL": "Databases",
    "MongoDB": "Databases",
    "SQLite": "Databases",
    "Redis": "Databases",
    "Kafka": "Databases",
    "AWS": "Cloud & DevOps",
    "Azure": "Cloud & DevOps",
    "GCP": "Cloud & DevOps",
    "Docker": "Cloud & DevOps",
    "Kubernetes": "Cloud & DevOps",
    "Git": "Cloud & DevOps",
    "Linux": "Cloud & DevOps",
    "CI/CD": "Cloud & DevOps",
    "HTML": "Frontend",
    "CSS": "Frontend",
    "React": "Frontend",
    "Streamlit": "Frontend",
    "Selenium": "Quality & Automation",
    "Testing": "Quality & Automation",
    "Problem Solving": "Professional Skills",
    "Communication": "Professional Skills",
}

ROLE_SIGNATURES = {
    "NLP Engineer": {
        "skills": {"Python", "NLP", "spaCy", "NLTK", "TF-IDF", "Cosine Similarity", "Resume Parsing"},
        "keywords": {"nlp engineer", "language processing", "text mining", "resume analyzer"},
    },
    "AI Engineer": {
        "skills": {"Python", "Generative AI", "LLMs", "LangChain", "OpenAI API", "FastAPI"},
        "keywords": {"ai engineer", "llm", "generative ai", "prompt engineering"},
    },
    "ML Engineer": {
        "skills": {"Python", "Machine Learning", "Scikit-learn", "TensorFlow", "PyTorch", "Docker", "AWS"},
        "keywords": {"ml engineer", "machine learning engineer", "model deployment"},
    },
    "Backend Engineer": {
        "skills": {"Python", "FastAPI", "Flask", "Django", "REST API", "Microservices", "SQL", "Docker"},
        "keywords": {"backend engineer", "api engineer", "microservices"},
    },
    "Data Scientist": {
        "skills": {"Python", "Pandas", "NumPy", "Machine Learning", "Scikit-learn", "Data Analysis"},
        "keywords": {"data scientist", "predictive modeling", "analytics"},
    },
    "Data Engineer": {
        "skills": {"Python", "SQL", "ETL", "Airflow", "Spark", "Kafka", "AWS"},
        "keywords": {"data engineer", "pipeline", "warehouse", "etl"},
    },
    "Full Stack Developer": {
        "skills": {"JavaScript", "TypeScript", "React", "Node.js", "Express.js", "SQL", "HTML", "CSS"},
        "keywords": {"full stack", "frontend", "backend"},
    },
}
